name: omni_datetime_picker
description: "A datetime picker package with option to use a single datetime picker or a datetime range picker."
version: 2.0.6
repository: "https://github.com/alanchan-dev/OmniDateTimePicker"
homepage: "https://alanchan.dev"

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
